import { baseColors } from "./baseColors";

export const color = {
    accentText: baseColors.black,
    badgeBackground: baseColors.grey.light4,
    badgeText: baseColors.grey.dark2,
    cartButtonText: baseColors.grey.base,
    bannerBackground: baseColors.blue.base,
    buttonClear: 'transparent',
    buttonClearHover: baseColors.grey.light5,
    buttonPrimary: baseColors.grey.dark6,
    buttonPrimaryHover: baseColors.grey.dark5, // recheck
    buttonSecondary: baseColors.green.base,
    buttonSecondaryHover: baseColors.green.dark1, // recheck
    buttonText: baseColors.white,
    cardBackground: baseColors.grey.light6,
    checkoutTopBackground: baseColors.green.base,
    checkoutBottomBackground: baseColors.grey.light6,
    formBackground: baseColors.white,
    foodItemBackground: baseColors.white,
    footerBackground: baseColors.grey.dark5,
    headerBackground: baseColors.white,
    restaurantDetailBackground: baseColors.white,
    headerBorder: baseColors.grey.light4,
    inputBackground: baseColors.grey.light5,
    inputHint: baseColors.grey.dark1,
    inputIcon: baseColors.grey.dark6,
    label: baseColors.grey.dark4,
    labelActive: baseColors.grey.dark6,
    menuSectionBackground: baseColors.grey.light6,
    stepsIndicatorInnerBar: baseColors.grey.dark6,
    stepsIndicatorOuterBar: baseColors.grey.light5,
    orderSummaryBackground: baseColors.white,
    overlayBackground: baseColors.white,
    overlayHeader: baseColors.grey.light5,
    primaryText: baseColors.otherBlack,
    reviewText: baseColors.blue.dark5,
    screenBackground: baseColors.white,
    sidebarHeader: baseColors.grey.dark4,
    sidebarFooter: baseColors.white,
    skeletonBase: baseColors.grey.light4,
    skeletonHighlight: baseColors.grey.light5,
    topBannerBackground: baseColors.green.base,
    newRestaurantTag: baseColors.green.base,
    white: baseColors.white,
    black: baseColors.black,
}